# Generated by Django 2.1.3 on 2018-11-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe_ingredient',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipe_ingredient',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
