# Generated by Django 2.1.3 on 2018-11-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_planner', '0002_auto_20181104_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_ingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe_ingredient',
            name='recipe',
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ah_price',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='last_in_menu',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ManyToManyField(to='recipe_planner.Recipe'),
        ),
        migrations.DeleteModel(
            name='Recipe_ingredient',
        ),
    ]
