# Generated by Django 2.1.3 on 2018-11-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_planner', '0003_auto_20181110_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='recipe',
            new_name='recipes',
        ),
    ]
