# Generated by Django 2.1.3 on 2018-11-11 21:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_planner', '0005_auto_20181111_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='last_in_menu',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 11, 11, 21, 37, 31, 459505, tzinfo=utc), verbose_name='Last time this recipe was on menu'),
            preserve_default=False,
        ),
    ]
