# Generated by Django 2.1.3 on 2018-11-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_planner', '0008_auto_20181111_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='last_in_menu',
            field=models.DateField(blank=True, verbose_name='Last time this recipe was on menu'),
        ),
    ]
