# Generated by Django 2.1.3 on 2018-11-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_planner', '0009_auto_20181111_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='quisine',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
